

EGO_REG_CMD		= $d500
EGO_REG_STATUS		= $d501
EGO_REG_DATA		= $d502

EGO_CMD_RENDER_SPRITES	= 0
EGO_CMD_SET_WRITEABLE	= 1
EGO_CMD_SET_READONLY	= 2
EGO_CMD_ABORT		= 3
EGO_CMD_SHAPE_DATA	= 4
EGO_CMD_DEL_SHAPE	= 5
EGO_CMD_SPRITE_DATA	= 6
EGO_CMD_DEL_SPRITE	= 7
EGO_CMD_ENA_SPRITE	= 8
EGO_CMD_DIS_SPRITE	= 9
EGO_CMD_SET_SPRITE_X	= 10
EGO_CMD_SET_SPRITE_Y	= 11
EGO_CMD_SET_SPRITE_XY	= 12
EGO_CMD_SET_BLIT_WIDTH	= 13
EGO_CMD_SET_BLIT_HEIGHT	= 14
EGO_CMD_LINE_PTR	= 15
EGO_CMD_FILL_MEM	= 16
EGO_CMD_SPRITE_MODE	= 17
EGO_CMD_MOVEMENT 	= 99

